preset: psr1

linting: true

enabled:
- alias_functions
- align_double_arrow
- align_equals
- braces
- concat_with_spaces
- duplicate_semicolon
- elseif
- ereg_to_preg
- extra_empty_lines
- function_call_space
- function_declaration
- function_typehint_space
- include
- indentation
- linefeed
- line_after_namespace
- list_commas
- lowercase_keywords
- method_argument_space
- method_separation
- multiline_array_trailing_comma
- multiline_spaces_before_semicolon
- multiple_use
- namespace_no_leading_whitespace
- new_with_braces
- no_blank_lines_after_class_opening
- no_blank_lines_before_namespace
- no_empty_lines_after_phpdocs
- operators_spaces
- ordered_use
- parenthesis
- php4_constructor
- phpdoc_align
- phpdoc_indent
- phpdoc_inline_tag
- phpdoc_order
- phpdoc_scalar
- phpdoc_separation
- phpdoc_short_description
- phpdoc_trim
- phpdoc_type_to_var
- phpdoc_types
- php_unit_construct
- php_unit_strict
- psr0
- short_array_syntax
- single_array_no_trailing_comma
- single_quote
- spaces_before_semicolon
- spaces_cast
- standardize_not_equal
- strict
- strict_param
- ternary_spaces
- trailing_spaces
- trim_array_spaces
- unary_operators_spaces
- unused_use
- visibility
- whitespacy_lines

disabled:
- psr4
