/// @file ansi.h
/// @brief color codes for ansk terminals
/// @author Gothic@TMI-2
/// @version 1.0.0
/// @date 2016-01-27

////////////////////////////////////////////////////////////////////////////////
// WARNING:                                                                   //
// Do not edit this file with ed!                                             //
// It will lose its magical powers and be reduced to messages that look like  //
// " [7m" because ed tends to strip out escape characters!                    //
////////////////////////////////////////////////////////////////////////////////

#ifndef __SEC_ANSI_H
#define __SEC_ANSK_H

#ifndef ESC
#define ESC         ""                // ANSI ESC
#endif
#ifndef BEEP
#define BEEP        ""
#endif

#define VT100_CSI           ESC + "["           // ANSI control sequence start

#define VT100_NOR           CSI+"2;37;0m"       // Puts everything back to normal

// Foreground Colors {{{
#define VT100_BLK           CSI+"30m"           // Black
#define VT100_RED           CSI+"31m"           // Red
#define VT100_GRN           CSI+"32m"           // Green
#define VT100_YEL           CSI+"33m"           // Yellow
#define VT100_BLU           CSI+"34m"           // Blue
#define VT100_MAG           CSI+"35m"           // Magenta
#define VT100_CYN           CSI+"36m"           // Cyan
#define VT100_WHT           CSI+"37m"           // White
// }}}
// High Intensity Foreground Colors {{{
#define VT100_HBLK          CSI+"1;30m"         // Black    Note: hi-black comes out as dark grey.
#define VT100_HRED          CSI+"1;31m"         // Red
#define VT100_HGRN          CSI+"1;32m"         // Green
#define VT100_HYEL          CSI+"1;33m"         // Yellow
#define VT100_HBLU          CSI+"1;34m"         // Blue
#define VT100_HMAG          CSI+"1;35m"         // Magenta
#define VT100_HCYN          CSI+"1;36m"         // Cyan
#define VT100_HWHT          CSI+"1;37m"         // White
// }}}
// Background Colors {{{
#define VT100_BBLK          CSI+"40m"           // Black
#define VT100_BRED          CSI+"41m"           // Red
#define VT100_BGRN          CSI+"42m"           // Green
#define VT100_BYEL          CSI+"43m"           // Yellow
#define VT100_BBLU          CSI+"44m"           // Blue
#define VT100_BMAG          CSI+"45m"           // Magenta
#define VT100_BCYN          CSI+"46m"           // Cyan
#define VT100_BWHT          CSI+"47m"           // White
// }}}
// High Intensity Background Colors {{{
#define VT100_HBBLK         CSI+"40;1m"         // Black
#define VT100_HBRED         CSI+"41;1m"         // Red
#define VT100_HBGRN         CSI+"42;1m"         // Green
#define VT100_HBYEL         CSI+"43;1m"         // Yellow
#define VT100_HBBLU         CSI+"44;1m"         // Blue
#define VT100_HBMAG         CSI+"45;1m"         // Magenta
#define VT100_HBCYN         CSI+"46;1m"         // Cyan
#define VT100_HBWHT         CSI+"47;1m"         // White
// }}}

// Additional ansi Esc codes added to ansi.h by Gothic  april 23,1993
// Note:
// these are Esc codes for VT100 terminals, and emmulators and they may not
// all work within the mud

#define VT100_BOLD          CSI+"1m"            // Turn on bold mode
#define VT100_CLR           CSI+"2J"            // Clear the screen
#define VT100_HOME          CSI+"H"             // Send cursor to home position
#define VT100_REF           CLR+HOME            // Clear screen and home cursor
#define VT100_BIGTOP        ESC+"#3"            // Dbl height characters, top half
#define VT100_BIGBOT        ESC+"#4"            // Dbl height characters, bottem half
#define VT100_SAVEC         CSI+"s"             // Save cursor position
#define VT100_REST          CSI+"u"             // Restore cursor to saved position
#define VT100_REVINDEX      ESC+"M"             // Scroll screen in opposite direction
#define VT100_SINGW         ESC+"#5"            // Normal, single-width characters
#define VT100_DBL           ESC+"#6"            // Creates double-width characters
#define VT100_FRTOP         CSI+"2;25r"         // Freeze top line
#define VT100_FRBOT         CSI+"1;24r"         // Freeze bottom line
#define VT100_UNFR          CSI+"r"             // Unfreeze top and bottom lines
#define VT100_BLINK         CSI+"5m"            // Initialize blink mode
#define VT100_U             CSI+"4m"            // Initialize underscore mode
#define VT100_REV           CSI+"7m"            // Turns reverse video mode on
#define VT100_HIREV         CSI+"1,7m"          // Hi intensity reverse video

#define VT100_STRIP_ME  ({ VT100_NOR,                                   \
                        VT100_BLK, VT100_HBLK, VT100_BBLK, VT100_HBBLK, \
                        VT100_RED, VT100_HRED, VT100_BRED, VT100_HBRED, \
                        VT100_GRN, VT100_HGRN, VT100_BGRN, VT100_HBGRN, \
                        VT100_YEL, VT100_HYEL, VT100_BYEL, VT100_HBYEL, \
                        VT100_BLU, VT100_HBLU, VT100_BBLU, VT100_HBBLU, \
                        VT100_MAG, VT100_HMAG, VT100_BMAG, VT100_HBMAG, \
                        VT100_CYN, VT100_HCYN, VT100_BCYN, VT100_HBCYN, \
                        VT100_WHT, VT100_HWHT, VT100_BWHT, VT100_HBWHT, \
                        VT100_BOLD, VT100_CLR, VT100_HOME, VT100_REF,   \
                        VT100_BIGTOP, VT100_BIGBOT, VT100_SAVEC,        \
                        VT100_REST, VT100_REVINDEX, VT100_SINGW,        \
                        VT100_DBL, VT100_FRTOP, VT100_FRBOT,            \
                        VT100_UNFR, VT100_BLINK, VT100_U, VT100_REV,    \
                        VT100_HIREV })

#endif // __SEC_ANSK_H
